platform :ios, '9.0'

use_frameworks!

target 'AKFloatingLabel_Example' do
  
  pod 'AKFloatingLabel', :path => '../'
  pod 'SketchKit'

  target 'AKFloatingLabel_Tests' do
    inherit! :search_paths
  end
end
