platform :ios, '9.0'

use_frameworks!

target 'AKFloatingLabel_Example' do
  pod 'AKFloatingLabel', :path => '../'

  target 'AKFloatingLabel_Tests' do
    inherit! :search_paths

    pod 'Quick'
  	pod 'Nimble'
  	pod 'FBSnapshotTestCase'
  	pod 'Nimble-Snapshots'
  end
end
